// flow-typed signature: 1acc6254249f16a49443b3677e010479
// flow-typed version: <<STUB>>/d3_v^4.4.4/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'd3' {
    declare type D3Selection = {
        append: any,
        attr: any,
        call: any,
        classed: any,
        constructor: any,
        data: any,
        datum: any,
        dispatch: any,
        each: any,
        empty: any,
        enter: any,
        exit: any,
        filter: any,
        html: any,
        insert: any,
        interrupt: any,
        lower: any,
        merge: any,
        node: any,
        nodes: any,
        on: any,
        order: any,
        property: any,
        raise: any,
        remove: any,
        select: (selector: string) => D3Selection,
        selectAll: (selector: string) => D3Selection,
        size: any,
        sort: any,
        style: any,
        text: any,
        transition: any
    }

    declare module.exports: {
        axisBottom: any,
        extent: any,
        scaleLinear: any,
        select: (selector: string) => D3Selection,
        selectAll: (selector: string) => D3Selection
    }
}
